### ISSUE TITLE
about average camera pose

### ISSUE THREAD

**Issue by TaekyungKi** [oneThousand1000/LPFF-dataset#2]
Thank you for your interesting works.
Can I ask how to calculate average camera pose parameters in test time fine-tuning? Did you separately calculate average of elements of intrinsic matrix (3x3) and extrinsic (4x4)?
If so, the intrinsics are same throughout the dataset (https://github.com/NVlabs/eg3d/issues/100) except the skew parameter, right?

**Comment by oneThousand1000** [comment]
hi! I directly use the LookAtPoseSampler to calculate extrinsic matrix as avg camera, like:

https://github.com/NVlabs/eg3d/blob/7cf1fd1e99e1061e8b6ba850f91c94fe56e7afe4/eg3d/gen_samples.py#L156

I set both of horizontal_mean and vertical_mean as pi/2.

As for intrinsic parameters, I also fix it as eg3d dose, you can just keep it unchanged.

**Comment by TaekyungKi** [comment]
I got it.
Thanks for the super fast reply!
